/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-10-01 01:58:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1664337675212L));
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1664294358090L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1664332727026L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- content-section-starts -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"products-page\">\r\n");
      out.write("		<div class=\"products\">\r\n");
      out.write("			<div class=\"product-listy\">\r\n");
      out.write("				<h2>our Products</h2>\r\n");
      out.write("				<ul class=\"product-list\">\r\n");
      out.write("					<li><a href=\"\">New Products</a></li>\r\n");
      out.write("					<li><a href=\"\">Old Products</a></li>\r\n");
      out.write("					<li><a href=\"\">T-shirts</a></li>\r\n");
      out.write("					<li><a href=\"\">pants</a></li>\r\n");
      out.write("					<li><a href=\"\">Dress</a></li>\r\n");
      out.write("					<li><a href=\"\">Shorts</a></li>\r\n");
      out.write("					<li><a href=\"#\">Shirts</a></li>\r\n");
      out.write("					<li><a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">Register</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"latest-bis\">\r\n");
      out.write("				<img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("				<div class=\"offer\">\r\n");
      out.write("					<p>40%</p>\r\n");
      out.write("					<small>Top Offer</small>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tags\">\r\n");
      out.write("				<h4 class=\"tag_head\">Tags Widget</h4>\r\n");
      out.write("				<ul class=\"tags_links\">\r\n");
      out.write("					<li><a href=\"#\">Kitesurf</a></li>\r\n");
      out.write("					<li><a href=\"#\">Super</a></li>\r\n");
      out.write("					<li><a href=\"#\">Duper</a></li>\r\n");
      out.write("					<li><a href=\"#\">Theme</a></li>\r\n");
      out.write("					<li><a href=\"#\">Men</a></li>\r\n");
      out.write("					<li><a href=\"#\">Women</a></li>\r\n");
      out.write("					<li><a href=\"#\">Equipment</a></li>\r\n");
      out.write("					<li><a href=\"#\">Best</a></li>\r\n");
      out.write("					<li><a href=\"#\">Accessories</a></li>\r\n");
      out.write("					<li><a href=\"#\">Men</a></li>\r\n");
      out.write("					<li><a href=\"#\">Apparel</a></li>\r\n");
      out.write("					<li><a href=\"#\">Super</a></li>\r\n");
      out.write("					<li><a href=\"#\">Duper</a></li>\r\n");
      out.write("					<li><a href=\"#\">Theme</a></li>\r\n");
      out.write("					<li><a href=\"#\">Responsive</a></li>\r\n");
      out.write("					<li><a href=\"#\">Women</a></li>\r\n");
      out.write("					<li><a href=\"#\">Equipment</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"new-product\">\r\n");
      out.write("			<div class=\"col-md-5 zoom-grid\">\r\n");
      out.write("				<div class=\"flexslider\">\r\n");
      out.write("					<ul class=\"slides\">\r\n");
      out.write("						<li data-thumb=\"images/si.jpg\">\r\n");
      out.write("							<div class=\"thumb-image\">\r\n");
      out.write("								<img src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" data-imagezoom=\"true\"\r\n");
      out.write("									class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li data-thumb=\"images/si1.jpg\">\r\n");
      out.write("							<div class=\"thumb-image\">\r\n");
      out.write("								<img src=\"images/si1.jpg\" data-imagezoom=\"true\"\r\n");
      out.write("									class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li data-thumb=\"images/si2.jpg\">\r\n");
      out.write("							<div class=\"thumb-image\">\r\n");
      out.write("								<img src=\"images/si2.jpg\" data-imagezoom=\"true\"\r\n");
      out.write("									class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-7 dress-info\">\r\n");
      out.write("				<div class=\"dress-name\">\r\n");
      out.write("					<h3>LOREM IPSUM DRESS</h3>\r\n");
      out.write("					<span>$459.00</span>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("					<p>Sed ut perspiciatis unde omnis iste natus error sit\r\n");
      out.write("						voluptatem accusantium doloremque laudantium, totam rem aperiam,\r\n");
      out.write("						eaque ipsa quae ab illo inventore veritatis et quasi architecto\r\n");
      out.write("						beatae vitae dicta sunt explicabo</p>\r\n");
      out.write("					<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("						typesetting industry. Lorem Ipsum has been the industry's standard\r\n");
      out.write("						dummy text ever</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"span span1\">\r\n");
      out.write("					<p class=\"left\">FABRIC ORIGIN</p>\r\n");
      out.write("					<p class=\"right\">Japan</p>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"span span2\">\r\n");
      out.write("					<p class=\"left\">MADE IN</p>\r\n");
      out.write("					<p class=\"right\">China</p>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"span span3\">\r\n");
      out.write("					<p class=\"left\">COLOR</p>\r\n");
      out.write("					<p class=\"right\">White</p>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"span span4\">\r\n");
      out.write("					<p class=\"left\">SIZE</p>\r\n");
      out.write("					<p class=\"right\">\r\n");
      out.write("						<span class=\"selection-box\"><select class=\"domains valid\"\r\n");
      out.write("							name=\"domains\">\r\n");
      out.write("								<option>M</option>\r\n");
      out.write("								<option>L</option>\r\n");
      out.write("								<option>XL</option>\r\n");
      out.write("								<option>FS</option>\r\n");
      out.write("								<option>S</option>\r\n");
      out.write("						</select></span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"purchase\">\r\n");
      out.write("					<a href=\"#\">Purchase Now</a>\r\n");
      out.write("					<div class=\"social-icons\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a class=\"facebook1\" href=\"#\"></a></li>\r\n");
      out.write("							<li><a class=\"twitter1\" href=\"#\"></a></li>\r\n");
      out.write("							<li><a class=\"googleplus1\" href=\"#\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<script src=\"js/imagezoom.js\"></script>\r\n");
      out.write("				<!-- FlexSlider -->\r\n");
      out.write("				<script defer src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("				<script>\r\n");
      out.write("					// Can also be used with $(document).ready()\r\n");
      out.write("					$(window).load(function() {\r\n");
      out.write("						$('.flexslider').flexslider({\r\n");
      out.write("							animation : \"slide\",\r\n");
      out.write("							controlNav : \"thumbnails\"\r\n");
      out.write("						});\r\n");
      out.write("					});\r\n");
      out.write("				</script>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("			<div class=\"reviews-tabs\">\r\n");
      out.write("				<!-- Main component for a primary marketing message or call to action -->\r\n");
      out.write("				<ul class=\"nav nav-tabs responsive hidden-xs hidden-sm\" id=\"myTab\">\r\n");
      out.write("					<li class=\"test-class active\"><a class=\"deco-none misc-class\"\r\n");
      out.write("						href=\"#how-to\"> More Information</a></li>\r\n");
      out.write("					<li class=\"test-class\"><a href=\"#features\">Specifications</a></li>\r\n");
      out.write("					<li class=\"test-class\"><a class=\"deco-none\" href=\"#source\">Reviews\r\n");
      out.write("							(7)</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"tab-content responsive hidden-xs hidden-sm\">\r\n");
      out.write("					<div class=\"tab-pane active\" id=\"how-to\">\r\n");
      out.write("						<p class=\"tab-text\">Maecenas mauris velit, consequat sit amet\r\n");
      out.write("							feugiat rit, elit vitaeert scelerisque elementum, turpis nisl\r\n");
      out.write("							accumsan ipsum Lorem Ipsum is simply dummy text of the printing\r\n");
      out.write("							and typesetting industry. and scrambled it to make a type\r\n");
      out.write("							specimen book. It has survived Auction your website on Flippa and\r\n");
      out.write("							you'll get the best price from serious buyers, dedicated support\r\n");
      out.write("							and a much better deal than you'll find with any website broker.\r\n");
      out.write("							Sell your site today I need a twitter bootstrap 3.0 theme for the\r\n");
      out.write("							full-calendar plugin. it would be great if the theme includes the\r\n");
      out.write("							add event; remove event, show event details. this must be\r\n");
      out.write("							RESPONSIVE and works on mobile devices. Also, I've seen so many\r\n");
      out.write("							bootstrap themes that comes up with the fullcalendar plugin.\r\n");
      out.write("							However these .</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"tab-pane\" id=\"features\">\r\n");
      out.write("						<p class=\"tab-text\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("							adipiscing elit. Vestibulum nibh urna, euismod ut ornare non,\r\n");
      out.write("							volutpat vel tortor. Integer laoreet placerat suscipit. Sed\r\n");
      out.write("							sodales scelerisque commodo. Nam porta cursus lectus. Proin nunc\r\n");
      out.write("							erat, gravida a facilisis quis, ornare id lectus. Proin\r\n");
      out.write("							consectetur nibh quis urna gravida mollis.This tab has icon in\r\n");
      out.write("							consectetur adipiscing eliconse consectetur adipiscing elit.\r\n");
      out.write("							Vestibulum nibh urna, ctetur adipiscing elit. Vestibulum nibh\r\n");
      out.write("							urna, t.consectetur adipiscing elit. Vestibulum nibh urna,\r\n");
      out.write("							Vestibulum nibh urna,it.</p>\r\n");
      out.write("						<p class=\"tab-text\">Lorem ipsum dolor sit amet, consectetur\r\n");
      out.write("							adipisicing elit,There are many variations of passages of Lorem\r\n");
      out.write("							Ipsum available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("							dolore magna aliqua.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"tab-pane\" id=\"source\">\r\n");
      out.write("						<div class=\"response\">\r\n");
      out.write("							<div class=\"media response-info\">\r\n");
      out.write("								<div class=\"media-left response-text-left\">\r\n");
      out.write("									<a href=\"#\"> <img class=\"media-object\"\r\n");
      out.write("										src=\"images/icon1.png\" alt=\"\" />\r\n");
      out.write("									</a>\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"#\">Username</a>\r\n");
      out.write("									</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"media-body response-text-right\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit,There are many variations of passages of Lorem Ipsum\r\n");
      out.write("										available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua.</p>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>MARCH 21, 2015</li>\r\n");
      out.write("										<li><a href=\"single.html\">Reply</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media response-info\">\r\n");
      out.write("								<div class=\"media-left response-text-left\">\r\n");
      out.write("									<a href=\"#\"> <img class=\"media-object\"\r\n");
      out.write("										src=\"images/icon1.png\" alt=\"\" />\r\n");
      out.write("									</a>\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"#\">Username</a>\r\n");
      out.write("									</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"media-body response-text-right\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit,There are many variations of passages of Lorem Ipsum\r\n");
      out.write("										available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua.</p>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>MARCH 26, 2054</li>\r\n");
      out.write("										<li><a href=\"single.html\">Reply</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media response-info\">\r\n");
      out.write("								<div class=\"media-left response-text-left\">\r\n");
      out.write("									<a href=\"#\"> <img class=\"media-object\"\r\n");
      out.write("										src=\"images/icon1.png\" alt=\"\" />\r\n");
      out.write("									</a>\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"#\">Username</a>\r\n");
      out.write("									</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"media-body response-text-right\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit,There are many variations of passages of Lorem Ipsum\r\n");
      out.write("										available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua.</p>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>MAY 25, 2015</li>\r\n");
      out.write("										<li><a href=\"single.html\">Reply</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media response-info\">\r\n");
      out.write("								<div class=\"media-left response-text-left\">\r\n");
      out.write("									<a href=\"#\"> <img class=\"media-object\"\r\n");
      out.write("										src=\"images/icon1.png\" alt=\"\" />\r\n");
      out.write("									</a>\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"#\">Username</a>\r\n");
      out.write("									</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"media-body response-text-right\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit,There are many variations of passages of Lorem Ipsum\r\n");
      out.write("										available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua.</p>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>FEB 13, 2015</li>\r\n");
      out.write("										<li><a href=\"single.html\">Reply</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media response-info\">\r\n");
      out.write("								<div class=\"media-left response-text-left\">\r\n");
      out.write("									<a href=\"#\"> <img class=\"media-object\"\r\n");
      out.write("										src=\"images/icon1.png\" alt=\"\" />\r\n");
      out.write("									</a>\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"#\">Username</a>\r\n");
      out.write("									</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"media-body response-text-right\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit,There are many variations of passages of Lorem Ipsum\r\n");
      out.write("										available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua.</p>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>JAN 28, 2015</li>\r\n");
      out.write("										<li><a href=\"single.html\">Reply</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media response-info\">\r\n");
      out.write("								<div class=\"media-left response-text-left\">\r\n");
      out.write("									<a href=\"#\"> <img class=\"media-object\"\r\n");
      out.write("										src=\"images/icon1.png\" alt=\"\" />\r\n");
      out.write("									</a>\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"#\">Username</a>\r\n");
      out.write("									</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"media-body response-text-right\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit,There are many variations of passages of Lorem Ipsum\r\n");
      out.write("										available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua.</p>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>APR 18, 2015</li>\r\n");
      out.write("										<li><a href=\"single.html\">Reply</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"media response-info\">\r\n");
      out.write("								<div class=\"media-left response-text-left\">\r\n");
      out.write("									<a href=\"#\"> <img class=\"media-object\"\r\n");
      out.write("										src=\"images/icon1.png\" alt=\"\" />\r\n");
      out.write("									</a>\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"#\">Username</a>\r\n");
      out.write("									</h5>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"media-body response-text-right\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit,There are many variations of passages of Lorem Ipsum\r\n");
      out.write("										available, sed do eiusmod tempor incididunt ut labore et\r\n");
      out.write("										dolore magna aliqua.</p>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li>DEC 25, 2014</li>\r\n");
      out.write("										<li><a href=\"single.html\">Reply</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"clearfix\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"other-products products-grid\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<h3 class=\"like text-center\">Related Products</h3>\r\n");
      out.write("		</header>\r\n");
      out.write("		<div class=\"col-md-4 product simpleCart_shelfItem text-center\">\r\n");
      out.write("			<a href=\"single.html\"><img src=\"images/p1.jpg\" alt=\"\" /></a>\r\n");
      out.write("			<div class=\"mask\">\r\n");
      out.write("				<a href=\"single.html\">Quick View</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<a class=\"product_name\" href=\"single.html\">Sed ut perspiciatis</a>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a class=\"item_add\" href=\"#\"><i></i> <span class=\"item_price\">$329</span></a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-4 product simpleCart_shelfItem text-center\">\r\n");
      out.write("			<a href=\"single.html\"><img src=\"images/p2.jpg\" alt=\"\" /></a>\r\n");
      out.write("			<div class=\"mask\">\r\n");
      out.write("				<a href=\"single.html\">Quick View</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<a class=\"product_name\" href=\"single.html\">great explorer</a>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a class=\"item_add\" href=\"#\"><i></i> <span class=\"item_price\">$599.8</span></a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-4 product simpleCart_shelfItem text-center\">\r\n");
      out.write("			<a href=\"single.html\"><img src=\"images/p3.jpg\" alt=\"\" /></a>\r\n");
      out.write("			<div class=\"mask\">\r\n");
      out.write("				<a href=\"single.html\">Quick View</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<a class=\"product_name\" href=\"single.html\">similique sunt</a>\r\n");
      out.write("			<p>\r\n");
      out.write("				<a class=\"item_add\" href=\"#\"><i></i> <span class=\"item_price\">$359.6</span></a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"clearfix\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- content-section-ends -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/user/product_details.jsp(19,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/register");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/user/product_details.jsp(23,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/template/user/images/l4.jpg");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/user/product_details.jsp(60,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/template/user/images/si.jpg");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
