/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-10-01 01:58:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1664337675212L));
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1664294358090L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1664332727026L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- content-section-starts -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"products-page\">\r\n");
      out.write("		<div class=\"products\">\r\n");
      out.write("			<div class=\"product-listy\">\r\n");
      out.write("				<h2>our Products</h2>\r\n");
      out.write("				<ul class=\"product-list\">\r\n");
      out.write("					<li><a href=\"\">New Products</a></li>\r\n");
      out.write("					<li><a href=\"\">Old Products</a></li>\r\n");
      out.write("					<li><a href=\"\">T-shirts</a></li>\r\n");
      out.write("					<li><a href=\"\">pants</a></li>\r\n");
      out.write("					<li><a href=\"\">Dress</a></li>\r\n");
      out.write("					<li><a href=\"\">Shorts</a></li>\r\n");
      out.write("					<li><a href=\"#\">Shirts</a></li>\r\n");
      out.write("					<li><a href=\"register.html\">Register</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"latest-bis\">\r\n");
      out.write("				<img src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("				<div class=\"offer\">\r\n");
      out.write("					<p>40%</p>\r\n");
      out.write("					<small>Top Offer</small>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"tags\">\r\n");
      out.write("				<h4 class=\"tag_head\">Tags Widget</h4>\r\n");
      out.write("				<ul class=\"tags_links\">\r\n");
      out.write("					<li><a href=\"#\">Kitesurf</a></li>\r\n");
      out.write("					<li><a href=\"#\">Super</a></li>\r\n");
      out.write("					<li><a href=\"#\">Duper</a></li>\r\n");
      out.write("					<li><a href=\"#\">Theme</a></li>\r\n");
      out.write("					<li><a href=\"#\">Men</a></li>\r\n");
      out.write("					<li><a href=\"#\">Women</a></li>\r\n");
      out.write("					<li><a href=\"#\">Equipment</a></li>\r\n");
      out.write("					<li><a href=\"#\">Best</a></li>\r\n");
      out.write("					<li><a href=\"#\">Accessories</a></li>\r\n");
      out.write("					<li><a href=\"#\">Men</a></li>\r\n");
      out.write("					<li><a href=\"#\">Apparel</a></li>\r\n");
      out.write("					<li><a href=\"#\">Super</a></li>\r\n");
      out.write("					<li><a href=\"#\">Duper</a></li>\r\n");
      out.write("					<li><a href=\"#\">Theme</a></li>\r\n");
      out.write("					<li><a href=\"#\">Responsive</a></li>\r\n");
      out.write("					<li><a href=\"#\">Women</a></li>\r\n");
      out.write("					<li><a href=\"#\">Equipment</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"new-product\">\r\n");
      out.write("			<div class=\"new-product-top\">\r\n");
      out.write("				<ul class=\"product-top-list\">\r\n");
      out.write("					<li><a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">Home</a>&nbsp;<span>&gt;</span></li>\r\n");
      out.write("					<li><span class=\"act\">Best Sales</span>&nbsp;</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<p class=\"back\">\r\n");
      out.write("					<a href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">Back to Previous</a>\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mens-toolbar\">\r\n");
      out.write("				<div class=\"sort\">\r\n");
      out.write("					<div class=\"sort-by\">\r\n");
      out.write("						<label>Sort By</label> <select>\r\n");
      out.write("							<option value=\"\">Position</option>\r\n");
      out.write("							<option value=\"\">Name</option>\r\n");
      out.write("							<option value=\"\">Price</option>\r\n");
      out.write("						</select> <a href=\"\"><img src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" alt=\"\"\r\n");
      out.write("							class=\"v-middle\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul class=\"women_pagenation\">\r\n");
      out.write("					<li>Page:</li>\r\n");
      out.write("					<li class=\"active\"><a href=\"#\">1</a></li>\r\n");
      out.write("					<li><a href=\"#\">2</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"cbp-vm\" class=\"cbp-vm-switcher cbp-vm-view-grid\">\r\n");
      out.write("				<div class=\"cbp-vm-options\">\r\n");
      out.write("					<a href=\"#>\" class=\"cbp-vm-icon cbp-vm-grid cbp-vm-selected\"\r\n");
      out.write("						data-view=\"cbp-vm-view-grid\" title=\"grid\">Grid View</a> <a\r\n");
      out.write("						href=\"#\" class=\"cbp-vm-icon cbp-vm-list\"\r\n");
      out.write("						data-view=\"cbp-vm-view-list\" title=\"list\">List View</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"pages\">\r\n");
      out.write("					<div class=\"limiter visible-desktop\">\r\n");
      out.write("						<label>Show</label> <select>\r\n");
      out.write("							<option value=\"\" selected=\"selected\">9</option>\r\n");
      out.write("							<option value=\"\">15</option>\r\n");
      out.write("							<option value=\"\">30</option>\r\n");
      out.write("						</select> per page\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a class=\"cbp-vm-image\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("							<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("								<div class=\"view view-first\">\r\n");
      out.write("									<div class=\"inner_content clearfix\">\r\n");
      out.write("										<div class=\"product_image\">\r\n");
      out.write("											<img src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("											<div class=\"mask\">\r\n");
      out.write("												<div class=\"info\">Quick View</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"product_container\">\r\n");
      out.write("												<div class=\"cart-left\">\r\n");
      out.write("													<p class=\"title\">perspiciatis</p>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"pricey\">\r\n");
      out.write("													<span class=\"item_price\">$259.00</span>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"clearfix\"></div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("					</a>\r\n");
      out.write("						<div class=\"cbp-vm-details\">Silver beet shallot wakame\r\n");
      out.write("							tomatillo salsify mung bean beetroot groundnut.</div> <a\r\n");
      out.write("						class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li><a class=\"cbp-vm-image\" href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("					<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("						<div class=\"view view-first\">\r\n");
      out.write("							<div class=\"inner_content clearfix\">\r\n");
      out.write("								<div class=\"product_image\">\r\n");
      out.write("									<img src=\"images/p2.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("									<div class=\"mask\">\r\n");
      out.write("										<div class=\"info\">Quick View</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"product_container\">\r\n");
      out.write("										<div class=\"cart-left\">\r\n");
      out.write("											<p class=\"title\">Great Explorer</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"pricey\">\r\n");
      out.write("											<span class=\"item_price\">$189.00</span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("			</a>\r\n");
      out.write("				<div class=\"cbp-vm-details\">Wattle seed bunya nuts spring\r\n");
      out.write("					onion okra garlic bitterleaf zucchini.</div> <a\r\n");
      out.write("				class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li><a class=\"cbp-vm-image\" href=\"single.html\">\r\n");
      out.write("				<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("					<div class=\"view view-first\">\r\n");
      out.write("						<div class=\"inner_content clearfix\">\r\n");
      out.write("							<div class=\"product_image\">\r\n");
      out.write("								<img src=\"images/p3.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("								<div class=\"mask\">\r\n");
      out.write("									<div class=\"info\">Quick View</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"product_container\">\r\n");
      out.write("									<div class=\"cart-left\">\r\n");
      out.write("										<p class=\"title\">Similique Sunt</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"pricey\">\r\n");
      out.write("										<span class=\"item_price\">$699.00</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"clearfix\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("		</a>\r\n");
      out.write("			<div class=\"cbp-vm-details\">Kohlrabi bok choy broccoli rabe\r\n");
      out.write("				welsh onion spring onion tatsoi ricebean kombu chard.</div> <a\r\n");
      out.write("			class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	</li>\r\n");
      out.write("	<li><a class=\"cbp-vm-image\" href=\"single.html\">\r\n");
      out.write("			<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("				<div class=\"view view-first\">\r\n");
      out.write("					<div class=\"inner_content clearfix\">\r\n");
      out.write("						<div class=\"product_image\">\r\n");
      out.write("							<img src=\"images/p4.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("							<div class=\"mask\">\r\n");
      out.write("								<div class=\"info\">Quick View</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"product_container\">\r\n");
      out.write("								<div class=\"cart-left\">\r\n");
      out.write("									<p class=\"title\">Shrinking</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"pricey\">\r\n");
      out.write("									<span class=\"item_price\">$599.00</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("	</a>\r\n");
      out.write("		<div class=\"cbp-vm-details\">Kohlrabi bok choy broccoli rabe\r\n");
      out.write("			welsh onion spring onion tatsoi ricebean kombu chard.</div> <a\r\n");
      out.write("		class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a class=\"cbp-vm-image\" href=\"single.html\">\r\n");
      out.write("		<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("			<div class=\"view view-first\">\r\n");
      out.write("				<div class=\"inner_content clearfix\">\r\n");
      out.write("					<div class=\"product_image\">\r\n");
      out.write("						<img src=\"images/p5.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("						<div class=\"mask\">\r\n");
      out.write("							<div class=\"info\">Quick View</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_container\">\r\n");
      out.write("							<div class=\"cart-left\">\r\n");
      out.write("								<p class=\"title\">Perfectly Simple</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pricey\">\r\n");
      out.write("								<span class=\"item_price\">$459.00</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("</a>\r\n");
      out.write("	<div class=\"cbp-vm-details\">Kohlrabi bok choy broccoli rabe welsh\r\n");
      out.write("		onion spring onion tatsoi ricebean kombu chard.</div> <a\r\n");
      out.write("	class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("	</div></li>\r\n");
      out.write("<li><a class=\"cbp-vm-image\" href=\"single.html\">\r\n");
      out.write("		<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("			<div class=\"view view-first\">\r\n");
      out.write("				<div class=\"inner_content clearfix\">\r\n");
      out.write("					<div class=\"product_image\">\r\n");
      out.write("						<img src=\"images/p6.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("						<div class=\"mask\">\r\n");
      out.write("							<div class=\"info\">Quick View</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_container\">\r\n");
      out.write("							<div class=\"cart-left\">\r\n");
      out.write("								<p class=\"title\">Equal Blame</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pricey\">\r\n");
      out.write("								<span class=\"item_price\">$119.00</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("</a>\r\n");
      out.write("	<div class=\"cbp-vm-details\">Kohlrabi bok choy broccoli rabe welsh\r\n");
      out.write("		onion spring onion tatsoi ricebean kombu chard.</div> <a\r\n");
      out.write("	class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("	</div></li>\r\n");
      out.write("<li><a class=\"cbp-vm-image\" href=\"single.html\">\r\n");
      out.write("		<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("			<div class=\"view view-first\">\r\n");
      out.write("				<div class=\"inner_content clearfix\">\r\n");
      out.write("					<div class=\"product_image\">\r\n");
      out.write("						<img src=\"images/p7.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("						<div class=\"mask\">\r\n");
      out.write("							<div class=\"info\">Quick View</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_container\">\r\n");
      out.write("							<div class=\"cart-left\">\r\n");
      out.write("								<p class=\"title\">Neque Porro</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pricey\">\r\n");
      out.write("								<span class=\"item_price\">$289.00</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("</a>\r\n");
      out.write("	<div class=\"cbp-vm-details\">Kohlrabi bok choy broccoli rabe welsh\r\n");
      out.write("		onion spring onion tatsoi ricebean kombu chard.</div> <a\r\n");
      out.write("	class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("	</div></li>\r\n");
      out.write("<li><a class=\"cbp-vm-image\" href=\"single.html\">\r\n");
      out.write("		<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("			<div class=\"view view-first\">\r\n");
      out.write("				<div class=\"inner_content clearfix\">\r\n");
      out.write("					<div class=\"product_image\">\r\n");
      out.write("						<img src=\"images/p8.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("						<div class=\"mask\">\r\n");
      out.write("							<div class=\"info\">Quick View</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_container\">\r\n");
      out.write("							<div class=\"cart-left\">\r\n");
      out.write("								<p class=\"title\">Perfectly Simple</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pricey\">\r\n");
      out.write("								<span class=\"item_price\">$169.12</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("</a>\r\n");
      out.write("	<div class=\"cbp-vm-details\">Kohlrabi bok choy broccoli rabe welsh\r\n");
      out.write("		onion spring onion tatsoi ricebean kombu chard.</div> <a\r\n");
      out.write("	class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("	</div></li>\r\n");
      out.write("<li><a class=\"cbp-vm-image\" href=\"single.html\">\r\n");
      out.write("		<div class=\"simpleCart_shelfItem\">\r\n");
      out.write("			<div class=\"view view-first\">\r\n");
      out.write("				<div class=\"inner_content clearfix\">\r\n");
      out.write("					<div class=\"product_image\">\r\n");
      out.write("						<img src=\"images/p9.jpg\" class=\"img-responsive\" alt=\"\" />\r\n");
      out.write("						<div class=\"mask\">\r\n");
      out.write("							<div class=\"info\">Quick View</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"product_container\">\r\n");
      out.write("							<div class=\"cart-left\">\r\n");
      out.write("								<p class=\"title\">Praising Pain</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"pricey\">\r\n");
      out.write("								<span class=\"item_price\">$199.00</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("</a>\r\n");
      out.write("	<div class=\"cbp-vm-details\">Kohlrabi bok choy broccoli rabe welsh\r\n");
      out.write("		onion spring onion tatsoi ricebean kombu chard.</div> <a\r\n");
      out.write("	class=\"cbp-vm-icon cbp-vm-add item_add\" href=\"#\">Add to cart</a>\r\n");
      out.write("	</div></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- content-section-ends -->\r\n");
      out.write("<div class=\"other-products\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h3 class=\"like text-center\">Featured Collection</h3>\r\n");
      out.write("		<ul id=\"flexiselDemo3\">\r\n");
      out.write("			<li><a href=\"single.html\"><img src=\"images/l1.jpg\"\r\n");
      out.write("					class=\"img-responsive\" /></a>\r\n");
      out.write("				<div class=\"product liked-product simpleCart_shelfItem\">\r\n");
      out.write("					<a class=\"like_name\" href=\"single.html\">Perfectly simple</a>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a class=\"item_add\" href=\"#\"><i></i> <span class=\" item_price\">$759</span></a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li><a href=\"single.html\"><img src=\"images/l2.jpg\"\r\n");
      out.write("					class=\"img-responsive\" /></a>\r\n");
      out.write("				<div class=\"product liked-product simpleCart_shelfItem\">\r\n");
      out.write("					<a class=\"like_name\" href=\"single.html\">Praising pain</a>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a class=\"item_add\" href=\"#\"><i></i> <span class=\" item_price\">$699</span></a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li><a href=\"single.html\"><img src=\"images/l3.jpg\"\r\n");
      out.write("					class=\"img-responsive\" /></a>\r\n");
      out.write("				<div class=\"product liked-product simpleCart_shelfItem\">\r\n");
      out.write("					<a class=\"like_name\" href=\"single.html\">Neque porro</a>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a class=\"item_add\" href=\"#\"><i></i> <span class=\" item_price\">$329</span></a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li><a href=\"single.html\"><img src=\"images/l4.jpg\"\r\n");
      out.write("					class=\"img-responsive\" /></a>\r\n");
      out.write("				<div class=\"product liked-product simpleCart_shelfItem\">\r\n");
      out.write("					<a class=\"like_name\" href=\"single.html\">Equal blame</a>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a class=\"item_add\" href=\"#\"><i></i> <span class=\" item_price\">$499</span></a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li><a href=\"single.html\"><img src=\"images/l5.jpg\"\r\n");
      out.write("					class=\"img-responsive\" /></a>\r\n");
      out.write("				<div class=\"product liked-product simpleCart_shelfItem\">\r\n");
      out.write("					<a class=\"like_name\" href=\"single.html\">Perfectly simple</a>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a class=\"item_add\" href=\"#\"><i></i> <span class=\" item_price\">$649</span></a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("					 $(window).load(function() {\r\n");
      out.write("						$(\"#flexiselDemo3\").flexisel({\r\n");
      out.write("							visibleItems: 4,\r\n");
      out.write("							animationSpeed: 1000,\r\n");
      out.write("							autoPlay: true,\r\n");
      out.write("							autoPlaySpeed: 3000,    		\r\n");
      out.write("							pauseOnHover: true,\r\n");
      out.write("							enableResponsiveBreakpoints: true,\r\n");
      out.write("					    	responsiveBreakpoints: { \r\n");
      out.write("					    		portrait: { \r\n");
      out.write("					    			changePoint:480,\r\n");
      out.write("					    			visibleItems: 1\r\n");
      out.write("					    		}, \r\n");
      out.write("					    		landscape: { \r\n");
      out.write("					    			changePoint:640,\r\n");
      out.write("					    			visibleItems: 2\r\n");
      out.write("					    		},\r\n");
      out.write("					    		tablet: { \r\n");
      out.write("					    			changePoint:768,\r\n");
      out.write("					    			visibleItems: 3\r\n");
      out.write("					    		}\r\n");
      out.write("					    	}\r\n");
      out.write("					    });\r\n");
      out.write("					    \r\n");
      out.write("					});\r\n");
      out.write("				   </script>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- content-section-ends-here -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/user/products.jsp(22,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/template/user/images/l4.jpg");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/user/products.jsp(56,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/trang-chu");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/user/products.jsp(60,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/trang-chu");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/user/products.jsp(71,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/template/user/images/arrow2.gif");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/user/products.jsp(100,39) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/product_details");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/user/products.jsp(105,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/template/user/images/p1.jpg");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/user/products.jsp(127,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/product_details");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/user/products.jsp(340,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/template/user/js/cbpViewModeSwitch.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/user/products.jsp(341,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/template/user/js/classie.js");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/user/products.jsp(420,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/template/user/js/jquery.flexisel.js");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }
}
