/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-30 03:36:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1664337675212L));
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1664294358090L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1664332727026L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- registration-form -->\r\n");
      out.write("<div class=\"registration-form\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"dreamcrub\">\r\n");
      out.write("			<ul class=\"breadcrumbs\">\r\n");
      out.write("				<li class=\"home\"><a href=\"index.html\" title=\"Go to Home Page\">Home</a>&nbsp;\r\n");
      out.write("					<span>&gt;</span></li>\r\n");
      out.write("				<li class=\"women\">Registration</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"previous\">\r\n");
      out.write("				<li><a href=\"index.html\">Back to Previous Page</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<h2>Registration</h2>\r\n");
      out.write("		<div class=\"registration-grids\">\r\n");
      out.write("			<div class=\"reg-form\">\r\n");
      out.write("				<div class=\"reg\">\r\n");
      out.write("					<p>Welcome, please enter the following details to continue.</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						If you have previously registered with us, <a href=\"#\">click\r\n");
      out.write("							here</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<form>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"text-info\">First Name:</li>\r\n");
      out.write("							<li><input type=\"text\" value=\"\"></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"text-info\">Last Name:</li>\r\n");
      out.write("							<li><input type=\"text\" value=\"\"></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"text-info\">Email:</li>\r\n");
      out.write("							<li><input type=\"text\" value=\"\"></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"text-info\">Password:</li>\r\n");
      out.write("							<li><input type=\"password\" value=\"\"></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"text-info\">Re-enter Password:</li>\r\n");
      out.write("							<li><input type=\"password\" value=\"\"></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"text-info\">Mobile Number:</li>\r\n");
      out.write("							<li><input type=\"text\" value=\"\"></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<input type=\"submit\" value=\"REGISTER NOW\">\r\n");
      out.write("						<p class=\"click\">\r\n");
      out.write("							By clicking this button, you are agree to my <a href=\"#\">Policy\r\n");
      out.write("								Terms and Conditions.</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"reg-right\">\r\n");
      out.write("				<h3>Completely Free Account</h3>\r\n");
      out.write("				<div class=\"strip\"></div>\r\n");
      out.write("				<p>Pellentesque neque leo, dictum sit amet accumsan non,\r\n");
      out.write("					dignissim ac mauris. Mauris rhoncus, lectus tincidunt tempus\r\n");
      out.write("					aliquam, odio libero tincidunt metus, sed euismod elit enim ut mi.\r\n");
      out.write("					Nulla porttitor et dolor sed condimentum. Praesent porttitor lorem\r\n");
      out.write("					dui, in pulvinar enim rhoncus vitae. Curabitur tincidunt, turpis ac\r\n");
      out.write("					lobortis hendrerit, ex elit vestibulum est, at faucibus erat ligula\r\n");
      out.write("					non neque.</p>\r\n");
      out.write("				<h3 class=\"lorem\">Lorem ipsum dolor.</h3>\r\n");
      out.write("				<div class=\"strip\"></div>\r\n");
      out.write("				<p>Tincidunt metus, sed euismod elit enim ut mi. Nulla porttitor\r\n");
      out.write("					et dolor sed condimentum. Praesent porttitor lorem dui, in pulvinar\r\n");
      out.write("					enim rhoncus vitae. Curabitur tincidunt, turpis ac lobortis\r\n");
      out.write("					hendrerit, ex elit vestibulum est, at faucibus erat ligula non\r\n");
      out.write("					neque.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- registration-form -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
