/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-29 02:05:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.decorators;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class web_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1664337675212L));
    _jspx_dependants.put("jar:file:/D:/NAM3/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-mvc/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1664294358090L));
    _jspx_dependants.put("/common/user/header.jsp", Long.valueOf(1664357531378L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1664332727026L));
    _jspx_dependants.put("/common/user/footer.jsp", Long.valueOf(1664417035257L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005fbody_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Eshop</title>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write(" \" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write(" \"></script>\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write(" \" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Eshop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!--webfont-->\r\n");
      out.write("<!-- for bootstrap working -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<!-- //for bootstrap working -->\r\n");
      out.write("<!-- cart -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<!-- cart -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header-section-starts -->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("	<div class=\"header-top-strip\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"header-top-left\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"account.html\"><span\r\n");
      out.write("							class=\"glyphicon glyphicon-user\"> </span>Login</a></li>\r\n");
      out.write("					<li><a href=\"register.html\"><span\r\n");
      out.write("							class=\"glyphicon glyphicon-lock\"> </span>Create an Account</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"header-right\">\r\n");
      out.write("				<div class=\"cart box_1\">\r\n");
      out.write("					<a href=\"checkout.html\">\r\n");
      out.write("						<h3>\r\n");
      out.write("							<span class=\"simpleCart_total\"> $0.00 </span> (<span\r\n");
      out.write("								id=\"simpleCart_quantity\" class=\"simpleCart_quantity\"> 0 </span>)<img\r\n");
      out.write("								src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("						</h3>\r\n");
      out.write("					</a>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"javascript:;\" class=\"simpleCart_empty\">Empty cart</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- header-section-ends -->\r\n");
      out.write("<div class=\"banner-top\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("					data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("					<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("						class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("						class=\"icon-bar\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"logo\">\r\n");
      out.write("					<h1>\r\n");
      out.write("						<a href=\"index.html\"><span>E</span> -Shop</a>\r\n");
      out.write("					</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--/.navbar-header-->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\"\r\n");
      out.write("				id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("				<ul class=\"nav navbar-nav\">\r\n");
      out.write("					<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("					<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("						data-toggle=\"dropdown\">Men <b class=\"caret\"></b></a>\r\n");
      out.write("						<ul class=\"dropdown-menu multi-column columns-3\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-sm-4\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>NEW IN</h6>\r\n");
      out.write("										<li><a href=\"products.html\">New In Clothing</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Bags</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Shoes</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Watches</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Grooming</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-4\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>CLOTHING</h6>\r\n");
      out.write("										<li><a href=\"products.html\">Polos & Tees</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Casual Shirts</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Casual Trousers</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Jeans</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Shorts & 3/4th</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Formal Shirts</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Formal Trousers</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Suits & Blazers</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Track Wear</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Inner Wear</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-4\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>WATCHES</h6>\r\n");
      out.write("										<li><a href=\"products.html\">Analog</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Chronograph</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Digital</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Watch Cases</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("						data-toggle=\"dropdown\">women <b class=\"caret\"></b></a>\r\n");
      out.write("						<ul class=\"dropdown-menu multi-column columns-3\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-sm-4\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>NEW IN</h6>\r\n");
      out.write("										<li><a href=\"products.html\">New In Clothing</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Bags</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Shoes</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Watches</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Beauty</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-4\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>CLOTHING</h6>\r\n");
      out.write("										<li><a href=\"products.html\">Polos & Tees</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Casual Shirts</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Casual Trousers</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Jeans</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Shorts & 3/4th</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Formal Shirts</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Formal Trousers</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Suits & Blazers</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Track Wear</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Inner Wear</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-4\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>WATCHES</h6>\r\n");
      out.write("										<li><a href=\"products.html\">Analog</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Chronograph</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Digital</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Watch Cases</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("						data-toggle=\"dropdown\">kids <b class=\"caret\"></b></a>\r\n");
      out.write("						<ul class=\"dropdown-menu multi-column columns-2\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-sm-6\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>NEW IN</h6>\r\n");
      out.write("										<li><a href=\"products.html\">New In Boys Clothing</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Girls Clothing</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Boys Shoes</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">New In Girls Shoes</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-6\">\r\n");
      out.write("									<ul class=\"multi-column-dropdown\">\r\n");
      out.write("										<h6>ACCESSORIES</h6>\r\n");
      out.write("										<li><a href=\"products.html\">Bags</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Watches</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Sun Glasses</a></li>\r\n");
      out.write("										<li><a href=\"products.html\">Jewellery</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"typography.html\">TYPO</a></li>\r\n");
      out.write("					<li><a href=\"contact.html\">CONTACT</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--/.navbar-collapse-->\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!--/.navbar-->\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_dec_005fbody_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- content-section-ends-here -->\r\n");
      out.write("<div class=\"news-letter\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"join\">\r\n");
      out.write("			<h6>JOIN OUR MAILING LIST</h6>\r\n");
      out.write("			<div class=\"sub-left-right\">\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" value=\"Enter Your Email Here\"\r\n");
      out.write("						onfocus=\"this.value = '';\"\r\n");
      out.write("						onblur=\"if (this.value == '') {this.value = 'Enter Your Email Here';}\" />\r\n");
      out.write("					<input type=\"submit\" value=\"SUBSCRIBE\" />\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"footer_top\">\r\n");
      out.write("			<div class=\"span_of_4\">\r\n");
      out.write("				<div class=\"col-md-3 span1_of_4\">\r\n");
      out.write("					<h4>Shop</h4>\r\n");
      out.write("					<ul class=\"f_nav\">\r\n");
      out.write("						<li><a href=\"#\">new arrivals</a></li>\r\n");
      out.write("						<li><a href=\"#\">men</a></li>\r\n");
      out.write("						<li><a href=\"#\">women</a></li>\r\n");
      out.write("						<li><a href=\"#\">accessories</a></li>\r\n");
      out.write("						<li><a href=\"#\">kids</a></li>\r\n");
      out.write("						<li><a href=\"#\">brands</a></li>\r\n");
      out.write("						<li><a href=\"#\">trends</a></li>\r\n");
      out.write("						<li><a href=\"#\">sale</a></li>\r\n");
      out.write("						<li><a href=\"#\">style videos</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 span1_of_4\">\r\n");
      out.write("					<h4>help</h4>\r\n");
      out.write("					<ul class=\"f_nav\">\r\n");
      out.write("						<li><a href=\"#\">frequently asked questions</a></li>\r\n");
      out.write("						<li><a href=\"#\">men</a></li>\r\n");
      out.write("						<li><a href=\"#\">women</a></li>\r\n");
      out.write("						<li><a href=\"#\">accessories</a></li>\r\n");
      out.write("						<li><a href=\"#\">kids</a></li>\r\n");
      out.write("						<li><a href=\"#\">brands</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 span1_of_4\">\r\n");
      out.write("					<h4>account</h4>\r\n");
      out.write("					<ul class=\"f_nav\">\r\n");
      out.write("						<li><a href=\"account.html\">login</a></li>\r\n");
      out.write("						<li><a href=\"register.html\">create an account</a></li>\r\n");
      out.write("						<li><a href=\"#\">create wishlist</a></li>\r\n");
      out.write("						<li><a href=\"checkout.html\">my shopping bag</a></li>\r\n");
      out.write("						<li><a href=\"#\">brands</a></li>\r\n");
      out.write("						<li><a href=\"#\">create wishlist</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 span1_of_4\">\r\n");
      out.write("					<h4>popular</h4>\r\n");
      out.write("					<ul class=\"f_nav\">\r\n");
      out.write("						<li><a href=\"#\">new arrivals</a></li>\r\n");
      out.write("						<li><a href=\"#\">men</a></li>\r\n");
      out.write("						<li><a href=\"#\">women</a></li>\r\n");
      out.write("						<li><a href=\"#\">accessories</a></li>\r\n");
      out.write("						<li><a href=\"#\">kids</a></li>\r\n");
      out.write("						<li><a href=\"#\">brands</a></li>\r\n");
      out.write("						<li><a href=\"#\">trends</a></li>\r\n");
      out.write("						<li><a href=\"#\">sale</a></li>\r\n");
      out.write("						<li><a href=\"#\">style videos</a></li>\r\n");
      out.write("						<li><a href=\"#\">login</a></li>\r\n");
      out.write("						<li><a href=\"#\">brands</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"cards text-center\">\r\n");
      out.write("			<img src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" alt=\"\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"copyright text-center\">\r\n");
      out.write("			<p>\r\n");
      out.write("				© 2015 Eshop. All Rights Reserved | Design by <a\r\n");
      out.write("					href=\"http://w3layouts.com\"> W3layouts</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /decorators/web.jsp(7,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/template/user/css/bootstrap.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /decorators/web.jsp(9,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/template/user/js/jquery.min.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /decorators/web.jsp(11,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/template/user/css/style.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /decorators/web.jsp(20,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/template/user/js/bootstrap-3.1.1.min.js");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /decorators/web.jsp(23,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/template/user/js/simpleCart.min.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /decorators/web.jsp(25,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/template/user/css/flexslider.css");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /common/user/header.jsp(21,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/template/web/images/bag.png");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_dec_005fbody_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:body
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jspx_th_dec_005fbody_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.BodyTag) _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class);
    boolean _jspx_th_dec_005fbody_005f0_reused = false;
    try {
      _jspx_th_dec_005fbody_005f0.setPageContext(_jspx_page_context);
      _jspx_th_dec_005fbody_005f0.setParent(null);
      int _jspx_eval_dec_005fbody_005f0 = _jspx_th_dec_005fbody_005f0.doStartTag();
      if (_jspx_th_dec_005fbody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.reuse(_jspx_th_dec_005fbody_005f0);
      _jspx_th_dec_005fbody_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_dec_005fbody_005f0, _jsp_getInstanceManager(), _jspx_th_dec_005fbody_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /common/user/footer.jsp(81,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/template/user/images/cards.jpg");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }
}
